// MithrilLedger — Tailwind Brand Theme
// Generated by systematic-dev-kit:brand-designer
//
// Usage: import in tailwind.config.js
//   const brandTheme = require('./brand/tailwind.brand.js');
//   module.exports = { theme: { extend: brandTheme } }

module.exports = {
  colors: {
    primary: {
      50: 'hsl(230 15% 97%)',
      100: 'hsl(230 14% 90%)',
      200: 'hsl(230 13% 78%)',
      300: 'hsl(230 13% 63%)',
      400: 'hsl(230 14% 46%)',
      500: 'hsl(230 15% 19%)',
      600: 'hsl(230 16% 15%)',
      700: 'hsl(230 17% 12%)',
      800: 'hsl(230 18% 9%)',
      900: 'hsl(230 20% 6%)',
      DEFAULT: 'hsl(var(--color-primary-h) var(--color-primary-s) var(--color-primary-l))',
    },
    secondary: {
      50: 'hsl(220 30% 97%)',
      100: 'hsl(220 28% 90%)',
      200: 'hsl(220 28% 80%)',
      300: 'hsl(220 30% 72%)',
      400: 'hsl(220 30% 65%)',
      500: 'hsl(220 28% 52%)',
      600: 'hsl(220 26% 42%)',
      700: 'hsl(220 24% 33%)',
      800: 'hsl(220 22% 24%)',
      900: 'hsl(220 20% 16%)',
      DEFAULT: 'hsl(var(--color-secondary-h) var(--color-secondary-s) var(--color-secondary-l))',
    },
    accent: {
      50: 'hsl(40 54% 96%)',
      100: 'hsl(40 50% 88%)',
      200: 'hsl(40 48% 76%)',
      300: 'hsl(40 50% 63%)',
      400: 'hsl(40 54% 50%)',
      500: 'hsl(40 58% 40%)',
      600: 'hsl(40 60% 32%)',
      700: 'hsl(40 62% 24%)',
      800: 'hsl(40 60% 18%)',
      900: 'hsl(40 55% 12%)',
      DEFAULT: 'hsl(var(--color-accent-h) var(--color-accent-s) var(--color-accent-l))',
    },
    // Semantic
    success: 'var(--color-success)',
    warning: 'var(--color-warning)',
    error: 'var(--color-error)',
    info: 'var(--color-info)',
  },
  fontFamily: {
    heading: ['var(--font-heading)'],
    body: ['var(--font-body)'],
    mono: ['var(--font-mono)'],
  },
  fontSize: {
    display: ['var(--text-display)', { lineHeight: 'var(--leading-tight)' }],
    h1: ['var(--text-h1)', { lineHeight: 'var(--leading-tight)' }],
    h2: ['var(--text-h2)', { lineHeight: 'var(--leading-tight)' }],
    h3: ['var(--text-h3)', { lineHeight: 'var(--leading-tight)' }],
    h4: ['var(--text-h4)', { lineHeight: 'var(--leading-normal)' }],
    'body-lg': ['var(--text-body-lg)', { lineHeight: 'var(--leading-relaxed)' }],
    body: ['var(--text-body)', { lineHeight: 'var(--leading-normal)' }],
    'body-sm': ['var(--text-body-sm)', { lineHeight: 'var(--leading-normal)' }],
    caption: ['var(--text-caption)', { lineHeight: 'var(--leading-normal)' }],
  },
  spacing: {
    xs: 'var(--space-xs)',
    sm: 'var(--space-sm)',
    md: 'var(--space-md)',
    lg: 'var(--space-lg)',
    xl: 'var(--space-xl)',
    '2xl': 'var(--space-2xl)',
    '3xl': 'var(--space-3xl)',
  },
  borderRadius: {
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    full: 'var(--radius-full)',
  },
  boxShadow: {
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
  },
  transitionDuration: {
    fast: '150ms',
    normal: '280ms',
    slow: '450ms',
  },
};
